package com.example.fixmate.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF3525CD)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF4F46E5)
val OnPrimaryContainer = Color(0xFFDAD7FF)
val Secondary = Color(0xFF006C49)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF6CF8BB)
val OnSecondaryContainer = Color(0xFF00714D)
val Tertiary = Color(0xFF684000)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF885500)
val OnTertiaryContainer = Color(0xFFFFD4A4)
val Background = Color(0xFFF8F9FF)
val OnBackground = Color(0xFF0B1C30)
val Surface = Color(0xFFF8F9FF)
val OnSurface = Color(0xFF0B1C30)
val OnSurfaceVariant = Color(0xFF464555)
val Outline = Color(0xFF777587)
val OutlineVariant = Color(0xFFC7C4D8)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val SurfaceVariant = Color(0xFFD3E4FE)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFEFF4FF)
val SurfaceContainer = Color(0xFFE5EEFF)
val SurfaceContainerHigh = Color(0xFFDCE9FF)
val SurfaceContainerHighest = Color(0xFFD3E4FE)
val TertiaryFixed = Color(0xFFFFDDB8)
val OnTertiaryFixed = Color(0xFF2A1700)
